### PR TITLE
Select colors that resemble resistor code colors 1-9

### PR DESCRIPTION
**Pull request by SkyGen**
- Select colors that resemble resistor code colors 1-9, visible on both dark & light themes
- Add a test project to illustrate the effect

### CODE REVIEW

**Comment by BrunoBlanes** [comment]
You can change the default color for each level in Visual Studio settings, you don't need a PR for this, however, as an electrical engineering student, I am intrigued to know how those colors turned out. Could you post a simple picture here as is in the `readme.md` file?

**Comment by SkyGen** [comment]
Dark Mode: 
image

Light Mode:
image

**Comment by madskristensen** [comment]
This is awesome. Thank you!! Since you've added an additional .sln file, the GitHub Actions workflow don't know how to build anymore. Could you possibly update the worklfow file to point directly to the RainbowBraces.sln file?

**Comment by SkyGen** [comment]
Thanks, Mads! Trying to figure out how to update the workflow file since this is the first time I've submitted a PR here! Also had one more change.

**Comment by madskristensen** [comment]
Do we need the new .sln file and projects you added? How about just removing them?

**Comment by SkyGen** [comment]
I updated the workflow file as follows. Not sure what the current dir is during the build, do I need to specify $(SolutionDir)RainbowBraces.sln ?

    - name: Build
      run: msbuild RainbowBraces.sln /v:m -restore /p:OutDir=\_built

**Comment by SkyGen** [comment]
Sorry, I made the last change before seeing your last response! Sure, I can change the workflow file back and remove the test project, NP! Standby for the update...

**Comment by SkyGen** [comment]
Remove test project - give her a try now, thanks!

**Comment by madskristensen** [comment]
Awesome. Thank you!!

**Comment by SkyGen** [comment]
Hey, thanks, Mads, for creating RainbowBraces! It's very cool and helps with every day work!

**Pull request merged**
