### PR TITLE
Support for PHP Tools for VS

### PR DESCRIPTION
**Pull request by Miloslav**

### CODE REVIEW

**Comment by madskristensen** [comment]
Nice, thank you @Miloslav

**Comment by Miloslav** [comment]
Thank you, @madskristensen !

May I ask if the built-in brace colorization in VS2022 is based on this extension? If not, could you please provide any guidance on how to extend it or whom to contact? I would like to ensure that it also supports PHP, if possible.

**Comment by lordfanger** [comment]
It was not based on. But was only a sign, that full VS developers would like to have that functionality. If you want to extend the built-in functionality you have to use https://developercommunity.visualstudio.com/VisualStudio

I keep using this extension because it is more capable, extensible and have vertical color lines ^^

**Comment by madskristensen** [comment]
@OlegTk might know

**Comment by olegtk** [comment]
No, built-in brace colorization in VS2022 is not based on this extension. We rely on language services to provide IBracePairTag instead, here is Roslyn implementation as a sample: https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/BracePairs/BracePairsTaggerProvider.cs

Or if you are using LSP and language configuration rules you can just specify rules for bracket pairs.

**Pull request merged**
