### PR TITLE
Experimental feature: Fix some bugs in C++ templates + some enhancements to core

### PR DESCRIPTION
**Pull request by lordfanger**
Improved extensibility to allow look for surrounding of braces. 
- Wrapped running matching logic to class MatchingContext usable in PairBuilder
- Allowed AllowanceResolver to return builders specific only to his file.

Updated C++ template feature to guess whether '<' or '>' is part of template based on their surrounding.

### CODE REVIEW

**Comment by 1821746019** [comment]
@madskristensen
I cannot wait to try the new version. Could you merge it as fast as possible?

**Comment by madskristensen** [comment]
Is this ready to merge or still WIP?

**Comment by lordfanger** [comment]
Ah, sorry. It is ready to merge. :) But still opt-out with experimental flag.

**Comment by madskristensen** [comment]
Thanks

**Pull request merged**
